Create HW1
AleksandraNovo/java pull request #1
Opened 2023-09-11 10:53 UTC by AleksandraNovo

2023-09-11 13:47 UTC, KozlovAV426 requested changes

2023-09-11 13:47 UTC, KozlovAV426 commented on HW1
> +public class Homework1 {
Название файла должно соответствовать public class'у, который в нем находится, то есть HW1 -> Homework1.java

2023-09-11 13:47 UTC, KozlovAV426 commented on HW1
> +        return 0;
по сигнатуре фунции можно сделать вывод, что она должна возвращать число - максимум из трех, ты его находишь, выводишь и возвращаешь 0, но почему 0?)) если нужно вернуть n, и убрать вывод в консоль в этом методе

2023-09-11 13:47 UTC, KozlovAV426 commented on HW1
> +        return Arrays.stream(nums).sum()/nums.length;
здесь все таки предполагался цикл, без использования стримов, и возвращать все таки среднее, а не 0

2023-09-11 13:47 UTC, KozlovAV426 commented on HW1
> +        for (int i = 0; i < arr.length-1; i++){
здесь тоже возвращать отсортированный массив + расставить пробелы между операторами

2023-09-11 13:47 UTC, KozlovAV426 commented on HW1
> +        if (arg >= 0) {
может тогда int absoluteValue = Math.abs(arg) и дальше его передавать в функции, чтоб не дублировать код

2023-09-16 10:25 UTC, KozlovAV426 requested changes

2023-09-16 10:25 UTC, KozlovAV426 commented on Homework1
> +        return (sum/nums.length);
return (sum / nums.length);
везде проверить пробелы

2023-09-16 10:25 UTC, KozlovAV426 commented on Homework1
> +            d2 += square[i][len- i - 1];
square[i][len - i - 1];

2023-09-16 10:25 UTC, KozlovAV426 commented on Homework1
> +        int[] reverse_arr = new int[arr.length];
camelCase в названии переменных - reverseArr, но лучше reversedArray

2023-09-27 18:29 UTC, ASemenovng commented
Файл должен иметь расширение .java

2023-09-27 18:36 UTC, ASemenovng requested changes

2023-09-27 18:36 UTC, ASemenovng commented on Homework1
> +public class Homework1 {
Файл должен иметь расширение .java

2023-09-27 18:36 UTC, ASemenovng commented on Homework1
> +    static int fact(int n) {
что будет, если передать 0 в параметры?

2023-09-27 18:36 UTC, ASemenovng commented on Homework1
> +    static BigInteger fact(BigInteger n) {
аналогично: что будет, если передать 0 в параметры?

2023-09-27 18:36 UTC, ASemenovng commented on Homework1
> +        return n.multiply(fact(n.subtract(BigInteger.ONE))); // multiply = *
комменты по типу //multiply = * не обязательны)

2023-09-27 18:36 UTC, ASemenovng commented on Homework1
> +        return (sum / nums.length);
1. Для чего скобочки?
2. Что будет, если вызвать average() без аргументов?

2023-09-27 18:36 UTC, ASemenovng commented on Homework1
> +        int[] reverseArr = new int[arr.length];
Можно ли как-то сделать без доп памяти?

2023-09-27 18:36 UTC, ASemenovng commented on Homework1
> +        int x = 0;
1. Переменные лучше не называть просто буквами, если это не итерирование, дай им осмысленные имена
2. Лучше объявлять переменную непосредственно перед ее использованием, поэтому y лучше объявить позже. (Иначе приходится глазами по коду искать, для чего она нужна - а это не очень хорошо)

2023-12-01 15:55 UTC, merged